if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ]; then
	start_sway_session() {
		if hash gnome-keyring-daemon >& /dev/null; then
			eval $(gnome-keyring-daemon --start 2> /dev/null)
			export SSH_AUTH_SOCK
		fi
		/usr/bin/synaptiko-sway-systemd-session start
		killall -u $USER gnome-keyring-daemon &> /dev/null
	}

	if [ $XDG_VTNR -le 2 ]; then
		start_sway_session
	fi
fi
