if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ]; then
	sway() {
		# setup GUI libraries to work properly under Wayland: https://wiki.archlinux.org/index.php/Wayland#GUI_libraries
		# FIXME it's too early for the below; neither Chromium nor Electron app will work with it
		# export GDK_BACKEND=wayland
		export MOZ_ENABLE_WAYLAND=1
		# FIXME Zoom doesn't work with this yet
		# export QT_QPA_PLATFORM=wayland-egl
		export CLUTTER_BACKEND=wayland
		export SDL_VIDEODRIVER=wayland
		export _JAVA_AWT_WM_NONREPARENTING=1
		unfunction sway
		exec dbus-launch --sh-syntax --exit-with-session \
			sway -V -d &> ~/.sway.log
	}

	if [ $XDG_VTNR -le 2 ]; then
		sway
	fi
fi
