git:
  autoFetch: true

refresher:
  fetchInterval: 600

gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - white
      - bold
    inactiveBorderColor:
      - white
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - reverse
