git:
  autoFetch: true

refresher:
  fetchInterval: 600

gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - reverse
