git:
    autoFetch: true

refresher:
  fetchInterval: 600

gui:
  theme:
    # TODO jprokop: add support for light theme!!!
    lightTheme: false
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - reverse
