if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ]; then
	sway() {
		# FIXME it's too early for the below; neither Chromium nor Electron app will work with it
		# export GDK_BACKEND=wayland
		unfunction sway
		unfunction i3
		exec dbus-launch --sh-syntax --exit-with-session \
			sway -V -d &> ~/.sway.log
	}

	i3() {
		unfunction sway
		unfunction i3
		exec startx >& /dev/null
	}

	if [ $XDG_VTNR -le 2 ]; then
		sway
	fi
fi
