#!/usr/bin/env bash
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

XRANDR_DIR=$HOME/.files/xrandr
HOSTNAME=`hostname`

if [ -f $XRANDR_DIR/$HOSTNAME/screenlayout.sh ]; then
	$XRANDR_DIR/$HOSTNAME/screenlayout.sh
fi

# bell sound off
xset b off
# screensaver: on, blank and after 5 minutes
xset s on
xset s blank
xset s 300 300

numlockx &
xbanish &

export QT_QPA_PLATFORMTHEME="qt5ct"
export WINIT_UNIX_BACKEND=x11

# to avoid huge delay when opening Nautilus or other gnome-based apps:
# https://github.com/flatpak/xdg-desktop-portal-gtk/issues/72
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

~/.files/i3/merge-config.sh

exec dbus-launch --sh-syntax --exit-with-session i3
