#!/usr/bin/env node
const yaml = require('js-yaml')
const fs = require('fs')
const path = require('path')
const colorSchemeFile = path.join(__dirname, 'gruvbox/colors.yml')
const rofiSchemeFile = path.join(__dirname, 'gruvbox/rofi.yml')
const sourceConfigFile = path.join(__dirname, 'configs/source-rofi-config.rasi')
const destinationConfigFile = path.join(__dirname, 'configs/rofi-config.rasi')
const theme = process.argv[2] || 'dark'

function loadYaml(yamlFile) {
	try {
		return yaml.safeLoad(fs.readFileSync(yamlFile, { encoding: 'utf8' }))
	} catch (e) {
		console.error(`Error while loading ${yamlFile}`)
		throw e
	}
}

const colorScheme = loadYaml(colorSchemeFile).colors
const rofiScheme = loadYaml(rofiSchemeFile)
const newRofiColors = Object.entries(rofiScheme[theme]).reduce((result, [ selector, props ]) => {
	result.push(`${selector} {`)
	result.push(...Object.entries(props).reduce((result, [ property, schemeColorName ]) => {
		result.push(`\t${property}: ${colorScheme[schemeColorName]};`)
		return result
	}, []))
	result.push('}\n')
	return result
}, []).join('\n')

const rofiConfig = fs.readFileSync(sourceConfigFile, { encoding: 'utf8' }).split('/* -- THEME MARKER -- */')[0]
const newRofiConfig = `/* DO NOT EDIT THIS FILE DIRECTLY! IT'S GENERATED FROM .FILES, EDIT IT THERE */\n${rofiConfig}${newRofiColors}`

fs.writeFileSync(destinationConfigFile, newRofiConfig, { encoding: 'utf8' })
