# Environment
export BROWSER=/usr/bin/xdg-open
export EDITOR=nvim
export VISUAL=nvim
export COLORTERM=gnome-terminal # fix for https://github.com/neovim/neovim/issues/6802 (remove when https://github.com/neovim/neovim/pull/6816 is merged)
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
export ANDROID_HOME=$HOME/Android/SDK
export JAVA_HOME=/usr/lib/jvm/java-8-jdk
export PATH=./node_modules/.bin:$PATH:$JAVA_HOME/bin:$HOME/.yarn/bin:$HOME/.local/opt/gcc-arm-none-eabi-6/bin

# NVIM_TUI_ENABLE_TRUE_COLOR is problematic in Gnome Terminal: when :term is called inside Neovim colors are incorrect
# But it can be resolved in init.vim like this: https://github.com/neovim/neovim/issues/4436
export NVIM_TUI_ENABLE_TRUE_COLOR=1
export NVIM_TUI_ENABLE_CURSOR_SHAPE=1

# Setting ag as the default source for fzf
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS='--height=100% --reverse --inline-info'

# History
HISTFILE=~/.zsh_history
HISTSIZE=100000000
SAVEHIST=$((HISTSIZE/2))
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

# Don't beep
unsetopt beep
if [ -n "$DISPLAY" ]; then
	xset b off
fi

# Use vi-like keys
bindkey -v

# Defaults for completion
zstyle :compinstall filename '$HOME/.zshrc'
zstyle ':completion:*' rehash true
autoload -Uz compinit
compinit

# work .files
if [ -d ~/.files-work/zsh ]; then
	for file in ~/.files-work/zsh/*.zsh; do
		source "$file"
	done
fi

# Use zplug as plugin manager!
source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

zplug 'plugins/vi-mode', from:oh-my-zsh
zplug 'plugins/sudo', from:oh-my-zsh
zplug '~/.files', from:local, use:'zsh/*.zsh'

# zplug 'halfo/lambda-mod', as:theme
zplug 'synaptiko/spaceship-zsh-theme', as:theme

# Spaceship theme configuration
SPACESHIP_PROMPT_SYMBOL='λ'
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_TRUNC=0
SPACESHIP_PREFIX_SHOW=true
SPACESHIP_PREFIX_HOST='@'
SPACESHIP_PREFIX_DIR=' in '
SPACESHIP_PREFIX_GIT='  '
SPACESHIP_PREFIX_ENV_DEFAULT=' via '
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_UNCOMMITTED='+'
SPACESHIP_GIT_UNSTAGED='!'
SPACESHIP_GIT_UNTRACKED='?'
SPACESHIP_GIT_STASHED='$'
SPACESHIP_GIT_UNPULLED='↓'
SPACESHIP_GIT_UNPUSHED='↑'
SPACESHIP_VI_MODE_SHOW=false
# maybe later switch to true
SPACESHIP_NVM_SHOW=false

if [ -e ~/.zsh-first-run ]; then
	rm ~/.zsh-first-run
	zplug install
fi

# if ! zplug check --verbose; then
# 	printf "Install? [y/N]: "
# 	if read -q; then
# 		echo; zplug install
# 	fi
# fi

zplug load

# FZF sourcing
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh

# NVM sourcing
export NVM_DIR="$HOME/.nvm"
[ -f /usr/share/nvm/init-nvm.sh ] && source /usr/share/nvm/init-nvm.sh
