# Environment
export BROWSER=/usr/bin/xdg-open
export EDITOR=nvim
export VISUAL=nvim
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
export ANDROID_HOME=$HOME/Android/SDK
export JAVA_HOME=/usr/lib/jvm/java-13-jdk
export PATH=./node_modules/.bin:$PATH:$JAVA_HOME/bin:$HOME/.yarn/bin:$HOME/.local/opt/gcc-arm-none-eabi-6/bin
export SUDO_ASKPASS=/usr/bin/lxqt-openssh-askpass
export OWNVIM_LISTEN_ADDRESS=/run/user/$UID/synaptiko-ownvim

# Prevent duplicates in PATH variable
typeset -U path

# NVIM_TUI_ENABLE_TRUE_COLOR was problematic but gruvbox colorscheme has already proper support for it
# (more info: https://github.com/morhetz/gruvbox/commit/e5c6c3a359af4b2da8f50ea9323315308f00d191
#  && https://github.com/neovim/neovim/issues/4436)
export NVIM_TUI_ENABLE_TRUE_COLOR=1

# Use vi-like keys
bindkey -v

# My plugins
local ZSH_PLUG_PATH=$HOME/.zsh_plug
fpath=( $ZSH_PLUG_PATH $fpath )

source $ZSH_PLUG_PATH/vi-mode.plugin.zsh
source $ZSH_PLUG_PATH/sudo.plugin.zsh

autoload -U promptinit; promptinit
prompt pure

# History
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000000
SAVEHIST=$((HISTSIZE/2))
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history
setopt auto_cd

# Don't beep
unsetopt beep
if [ -n "$DISPLAY" ]; then
	xset b off
fi

# Defaults for completion
zstyle :compinstall filename '$HOME/.zshrc'
zstyle ':completion:*' rehash true
autoload -Uz compinit
# disable check for unsafe locations by `-u`
# (unfortunately .zsh_plug under root is symlink
#  and it's impossible to set 755 permissions to it)
compinit -u

# Setting ag as the default source for fzf
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS='--height=100% --reverse --inline-info --color=16'

# FZF sourcing (load before my own zsh scripts to be able to override some keybindings)
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh

# .files
for file in $HOME/.files/zsh/*.zsh; do
	source "$file"
done

# work .files (optional)
if [ -d $HOME/.files-work/zsh ]; then
	for file in $HOME/.files-work/zsh/*.zsh; do
		source "$file"
	done
fi
